### ISSUE TITLE
Bundled GTest needs update

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#103]
**Describe the bug**
The currently bundled version of gtest does not suffice to compile the runTest target.

**To Reproduce**
1. Make sure gtest is not installed on your system
2. `make clean`
4. `make runTests`
5. See Error message:
```
In file included from /mnt/d/workspace/AutoPas/tests/testAutopas/AutoTunerTest.h:9:0,
                 from /mnt/d/workspace/AutoPas/tests/testAutopas/AutoTunerTest.cpp:7:
/mnt/d/workspace/AutoPas/cmake-build-manually/tests/gtest/src/gtest/googletest/include/gtest/gtest.h:62:36: fatal error: gtest/gtest-param-test.h: No such file or directory
compilation terminated.
```

**Expected behavior**
Successful compilation.

**Build environment (please complete the following information):**
all

**Additional context**
Works with [gtest Release 1.81](https://github.com/google/googletest/releases/tag/release-1.8.1).

**How to Fix**
Update bundled zip and hash check.
